language: php
install: true
script: tar zcf nyaa.dlm -C ./src INFO search.php
deploy:
  provider: releases
  api_key:
    secure: F3rQJl+cPZ300AMsYjrWki0iYHtkMku6hyDDZC8FNsOuiTVGMLJT4CU+91HpKyaRzBzLWvGf486bDMTPwedznesa2tDF/7rxMe9S9T16w1a7v4bUTnycL/78RRlTYhDoE61oORZJdYh+14VKS0KUSTqCKmovqoGPtVbd7E6TqNCJf71mbBPp50TRf8i4T8oLQGgmKBpL2b3F+PyzVxxdUo87XokJhzdz3qa48yYfhGKCVVub9BuYH8hWSfdDTZVg2+57G8SUDwwFH4QePkYkPCrjj5AgmkVOxRu/CcuWcSENzTKqk/yMs3rp1e6aYeQvT+8OrCGGndjJ26j6nw7qWQTWpAvEVVkdI8vJKb9+aT2i87ZboUnoidi6dRhysjtLO0qUNAEh7m8HhyRaRphXni0za0dyC8A7a7odk3PHqotELKIDZGzRl5lJl99yq8GmFGJgfjne+63SDLj7gFIjDRoBAEYDYNUBm7lVCPAQXTRNU9Gzs3uEe5N1tlvDwlbTBMGahAVbhpKNY8d31g2oLy9xo1ird7+OugoguvkShozkoU7nlJSMukYW3v6fPzWqx+7eUPLXEZc/SXu4rv4mbBC5YmFBX6svAwBzsXjA7lSH5kp/5ScFdVgO7ET8yALkpf7SWL/QfEXCQFvFLLl9VCEF5V71roD3EYPqVYjpxno=
  file: nyaa.dlm
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    tags: true
    repo: neobutter/SynoDLMSearchNyaa