language: php
install: true
script: tar zcf nyaa.dlm -C ./src INFO search.php
deploy:
  provider: releases
  api_key:
    secure: CZPXjtikj3ev2Ix7J1HHfxIJgMnp7/8OucLS3oTTpTLc0LZw0192hEVyvDnXgsi+VGH/3KfDUOEGh2H/zKT4zcph70Ii6O8jVcIUQhVdyh5+q0j58ITzpUWmPIEsGyDvBlk2uJ3tlzfiHi26qQAS6GfB8sMXaXcM4FRvipdDqjUNULGYQcdOmwSeoydC5BNm8gLkU66Y8e+ORELDHLDRKqBFy7kR3WgyXUvTfujepQM5tHQmnTR/Ah6y+8VEQ7tqeQ0cvcP3EkiN3XNiAeqq/cRW+FtEiD9YkjGPAmzTXx8q8Y5bYRI/K1/sAaICYE7kg3IRWdgpM9FBVJkXjDkEPL52aoFq1hpyPpRW4pQ8ZQm4Wk4HIrKVLXFWGoft5Pd7IeWFSMrhLMZiXkCRx+rCsMODfnqxeQsHsvyZdf5gAPXzbWEoMVAC0d0TDBe3EGC5cl5Zy8ialbvZ9iRrOoLgSigbM4EuFSHF7ONgquJNeOXunpEMVTWm5FIQjR/s2FpXJBgCldkLnHV/upplob2vCN2iYJWq4wMOolXbMqW2J6RwWmW4U76zyWXG7XYMe53wmnZJKYCQEIPCjfwSqR5DXOxQUfhp9nRnEP0PqJR4DnIx5kkZxABD8Y4bD9WGjzreFiX47ylC9d3DNRV16ymCUwDhrGCxdmuOn5hrbTHklfM=
  file: nyaa.dlm
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    tags: true
    repo: neobutter/SynoDLMSearchNyaa
