language: php
install: true
script: tar zcf nyaa.dlm -C ./src INFO search.php
deploy:
  provider: releases
  api_key:
    secure: k7yO4N3aXm+OxPR/KhJnRomKEFVNT97SYxZxtclm/yST+rCeg4KTkkuXDf9fLhy9TOGn4HfAFegKspbNy/rMstDcDseVG5X2Z4Q7YyaUgIEBqRo3r0fs1a6iZIvcXsvXZXrZ3j8hbF6jOBmGZEGzsot1k1dlFoPBq+rk5Op274iszcM2gToCsKiUzp3etZ3JEIPC9YrTPK4vvln1tKzX13MkncAVvGf3p/kc2myQmTOSNazheRdlsCeRrdQvzm88DvlZ9ZwVYSmSDkK6jPDFsICYsnvVHN3QZf3aKypw1DfO4btvrl3lBT4fY2ap85jZH6SqyF9ezgul12F8dg8qXj93WLZ8W0u5XJNw7qrKJ54wMCwkO6mzS6ucGk978aBeZaQJz1VYtBmiQbvFQMLUTXj34j4vRj9UYN5qjQFj2ZIlaT2JmzvPCdtjJR1RAPiFk32yGKcj45zLazJo5qqX+0MP98Bst+n9L6OgF/kzNWn+32mueROGEof7CsFisDV/dmCOIcoapvt5X6Kl2SQtn4tXCD3/ePVG7mv7cLa6HknGkfyZn2N+stM7iQnsQK2XRLVelMJx/6TbutOdk2I+XU80UsHLhWSy99zGOi0oNDavsYuhafOna+Gn/JsCPMKnTJLdheY65K0R94iR8wY6SQVojE5gqNSMvQxxXR8/B70=
  file: nyaa.dlm
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    tags: true
    repo: neobutter/SynoDLMSearchNyaa
